const String CLIENT_ID = 'CLIENT_ID';
const String CLIENT_NAME = 'NAME';
const String CLIENT_LAST_NAME = 'LAST_NAME';
const String CLIENT_GENDER =  'GENDER';
const String CLIENT_BIRTHDATE = 'BIRTHDATE';

const String ADDRESS_ID = 'ADDRESS_ID';
const String STREET_NUMBER = 'STREET_NUMBER';
const String STREET_NAME = 'STREET_NAME';
const String STREET_SUFFIX = 'STREET_SUFFIX';